# Generated by Django 3.1.2 on 2021-04-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
